### ISSUE TITLE
Recall is not compatible with atom-shell version of LightTable

### ISSUE THREAD

**Issue by seancorfield** [joshuafcole/recall#19]
Produces this error on loading:

```
[98258:1205/184723:INFO:CONSOLE(29920)] "Error loading JS file: /Users/sean/Library/Application Support/LightTable/plugins/Recall/index.js : Error: Cannot find module 'lib/recall'", source: file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (29920)
[98258:1205/184723:INFO:CONSOLE(29921)] "Error: Cannot find module 'lib/recall'
    at Function.Module._resolveFilename (module.js:344:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:373:17)
    at require (module.js:392:17)
    at Object.requireLocal [as require] (/Users/sean/Dropbox/PlainText/LightTable/plugins/Recall/node_modules/ltrap/index.js:70:7)
    at nodePluginBootstrap (/Users/sean/Library/Application%20Support/LightTable/plugins/Recall/index.js:23:22)
    at eval (/Users/sean/Library/Application%20Support/LightTable/plugins/Recall/index.js:25:3)
    at eval (native)
    at c (file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21445:64)
    at a (file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21453:18)", source: file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (29921)
```

**Comment by joshuafcole** [comment]
Recall currently relies on some NW-specific modules for eventing (in order
to save prior to exit). It should be a pretty small change once I look into
atom's eventing.

On Mon, Dec 8, 2014 at 3:42 PM, Sean Corfield notifications@github.com
wrote:

> Produces this error on loading:
> 
> [98258:1205/184723:INFO:CONSOLE(29920)] "Error loading JS file: /Users/sean/Library/Application Support/LightTable/plugins/Recall/index.js : Error: Cannot find module 'lib/recall'", source: file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (29920)
> [98258:1205/184723:INFO:CONSOLE(29921)] "Error: Cannot find module 'lib/recall'
>     at Function.Module._resolveFilename (module.js:344:15)
>     at Function.Module._load (module.js:286:25)
>     at Module.require (module.js:373:17)
>     at require (module.js:392:17)
>     at Object.requireLocal [as require](/Users/sean/Dropbox/PlainText/LightTable/plugins/Recall/node_modules/ltrap/index.js:70:7)
>     at nodePluginBootstrap (/Users/sean/Library/Application%20Support/LightTable/plugins/Recall/index.js:23:22)
>     at eval (/Users/sean/Library/Application%20Support/LightTable/plugins/Recall/index.js:25:3)
>     at eval (native)
>     at c (file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21445:64)
>     at a (file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js:21453:18)", source: file:///Developer/workspace/LightTable/deploy/core/node_modules/lighttable/bootstrap.js (29921)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/joshuafcole/recall/issues/19.

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by muhuk** [comment]
Just wanted to add I will really miss recall until this is fixed. It really helps getting into the zone when you have your files opened for you.

Thanks for creating it @joshuafcole
