### ISSUE TITLE
"Error: Cannot find module 'lib/recall'" with LT 0.8 alpha

### ISSUE THREAD

**Issue by thSoft** [joshuafcole/recall#21]
When starting Light Table 0.8 alpha, Recall throws the following errors:

```
Error loading JS file: /Users/thsoft/Library/Application Support/LightTable/plugins/Recall/index.js : Error: Cannot find module 'lib/recall'
Error: Cannot find module 'lib/recall'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.requireLocal [as require] (/Users/thsoft/Library/Application Support/LightTable/plugins/Recall/node_modules/ltrap/index.js:70:7)
    at nodePluginBootstrap (/Users/thsoft/Library/Application%20Support/LightTable/plugins/Recall/index.js:23:22)
    at eval (/Users/thsoft/Library/Application%20Support/LightTable/plugins/Recall/index.js:25:3)
    at eval (native)
    at c (file:///Applications/lighttable-0.8.0-alpha-mac/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21542:41)
    at a (file:///Applications/lighttable-0.8.0-alpha-mac/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21550:18)
```

**Comment by rrrnld** [comment]
I ran across the same problem. Is there any progress on this?
My complete stacktrace:

```
Error loading JS file: /Users/arnold/Library/Application Support/LightTable/plugins/Recall/index.js : Error: Cannot find module 'lib/recall'
bootstrap.js [30062]    lt.objs.plugins.__BEH__load_js
Error: Cannot find module 'lib/recall' at Function.Module._resolveFilename (module.js:336:15)
 at Function.Module._load (module.js:286:25) at Module.require (module.js:365:17)
 at require (module.js:384:17)
 at Object.requireLocal [as require] (/Users/arnold/Library/Application Support/LightTable/plugins/Recall/node_modules/ltrap/index.js:70:7)
 at nodePluginBootstrap (/Users/arnold/Library/Application%20Support/LightTable/plugins/Recall/index.js:23:22)
 at eval (/Users/arnold/Library/Application%20Support/LightTable/plugins/Recall/index.js:25:3)
 at eval (native)
 at c (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21545:41)
 at a (file:///Applications/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:21553:18)
bootstrap.js [30063]    lt.objs.plugins.__BEH__load_js
```

**Comment by rrrnld** [comment]
For anyone also trapped in this issue, this was also mentioned in https://github.com/joshuafcole/recall/issues/19 which pointed to the [reminisce plugin](https://github.com/JuliaIDE/Reminisce), which for me works without a flaw.

**Comment by ghost** [comment]
I can confirm the problem. It also isn't as @heyarne hinted at the reminisce plugin, it is this one. This is a:
- fresh LightTable stock release download (so not compiled locally)
- moved away `~/.config/LightTable` to somewhere else so no plugins installed

Reminisce plugin installs fine. Install this one, instantly:

![image](https://cloud.githubusercontent.com/assets/11848802/12099512/ee1bb79c-b320-11e5-8bf2-7048427ec189.png)

Also, uninstalling _this_ plugin fixes it. Hence it originates from here.

**Comment by rrrnld** [comment]
I was not trying to suggest that the error stems from the reminisce plugin, but that reminisce provides (from what I understand) similar functionality to this one while still being more actively maintained. Hope this helps.

**Comment by ghost** [comment]
Ah.. my bad :) Thanks for clarifying
